### ISSUE TITLE
App not running on local environment - missing .env parameters

### ISSUE THREAD

**Issue by LionelOrishane** [ichtrojan/nigerian-banks#14]
**_Please help provide guiduance here. We are building our Web app and need to call this service locally using the bankCode and BankLogo. But it won't run with the documentation here thus far. maybe i'm doing something wrong. PS i'm in MERN stack person, zero knowledge about GO. see below test.

My aim is actually to run this as a Container using Docker compose._**

root@mycreditchekb2c-mvp-1vcpu-2gb-intel-fra1-01:~/nigerian-banks# go run server.go
go: downloading github.com/ichtrojan/thoth v1.3.0
go: downloading github.com/gorilla/mux v1.7.4
go: downloading github.com/joho/godotenv v1.3.0
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/gorilla/securecookie v1.1.1
go: downloading github.com/jinzhu/gorm v1.9.16
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading gorm.io/gorm v1.20.12
go: extracting github.com/ichtrojan/thoth v1.3.0
go: extracting github.com/gorilla/mux v1.7.4
go: extracting github.com/joho/godotenv v1.3.0
go: extracting github.com/jinzhu/gorm v1.9.16
go: extracting github.com/rs/cors v1.7.0
go: extracting gorm.io/gorm v1.20.12
go: extracting github.com/gorilla/securecookie v1.1.1
go: extracting github.com/gorilla/websocket v1.4.2
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/jinzhu/now v1.1.1
go: extracting github.com/jinzhu/inflection v1.0.0
go: extracting github.com/lib/pq v1.1.1
go: extracting github.com/jinzhu/now v1.1.1
go: extracting github.com/go-sql-driver/mysql v1.5.0
go: finding github.com/gorilla/mux v1.7.4
go: finding github.com/gorilla/securecookie v1.1.1
go: finding github.com/gorilla/websocket v1.4.2
go: finding gorm.io/gorm v1.20.12
go: finding github.com/jinzhu/inflection v1.0.0
go: finding github.com/jinzhu/now v1.1.1
go: finding github.com/jinzhu/gorm v1.9.16
go: finding github.com/go-sql-driver/mysql v1.5.0
go: finding github.com/lib/pq v1.1.1
go: finding github.com/ichtrojan/thoth v1.3.0
go: finding github.com/joho/godotenv v1.3.0
go: finding github.com/rs/cors v1.7.0
2022/03/22 09:46:07 HORUS_DB_USER not set in .env
exit status 1

**Comment by ichtrojan** [comment]
Hello @LionelOrishane 

Apologies, the .env file should look like this:

PORT=9090
HOST=http://localhost:9090

HORUS_DB_USER=root
HORUS_DB_PASS=
HORUS_DB_HOST=127.0.0.1
HORUS_DB_NAME=horus
HORUS_DB_PORT=3306

HORUS_DASHBOARD_PORT=8089
HORUS_DASHBOARD_KEY=00000000

Please replace the values with the appropriate ones for your environment.

I'd update the docs later.

**Comment by LionelOrishane** [comment]
Thank you for your speedy response.

Does that include this as well? when i tried to run the docker-compose.yml file:


root@mycreditchekb2c-mvp-1vcpu-2gb-intel-fra1-01:~/nigerian-banks# docker compose logs
nigerian-banks-web-1  | go: github.com/ichtrojan/horus@v1.0.8: missing go.sum entry; to add it:
nigerian-banks-web-1  |         go mod download github.com/ichtrojan/horus
nigerian-banks-web-1  | go: downloading github.com/ichtrojan/thoth v1.3.0
nigerian-banks-web-1  | go: downloading github.com/gorilla/mux v1.7.4
nigerian-banks-web-1  | go: downloading github.com/joho/godotenv v1.3.0
nigerian-banks-web-1  | go: downloading github.com/rs/cors v1.7.0
nigerian-banks-web-1  | go: github.com/ichtrojan/horus@v1.0.8: missing go.sum entry; to add it:
nigerian-banks-web-1  |         go mod download github.com/ichtrojan/horus
root@mycreditchekb2c-mvp-1vcpu-2gb-intel-fra1-01:~/nigerian-banks# docker compose ps
NAME                   COMMAND              SERVICE             STATUS              PORTS
nigerian-banks-web-1   "go run server.go"   web                 exited (1)          
root@mycreditchekb2c-mvp-1vcpu-2gb-intel-fra1-01:~/nigerian-banks#

**Comment by LionelOrishane** [comment]
root@mycreditchekb2c-mvp-1vcpu-2gb-intel-fra1-01:/nigerian-banks# docker compose logs

nigerian-banks-web-1 | go: github.com/ichtrojan/horus@v1.0.8: missing go.sum entry; to add it:

nigerian-banks-web-1 | go mod download github.com/ichtrojan/horus

nigerian-banks-web-1 | go: downloading github.com/ichtrojan/thoth v1.3.0

nigerian-banks-web-1 | go: downloading github.com/gorilla/mux v1.7.4

nigerian-banks-web-1 | go: downloading github.com/joho/godotenv v1.3.0

nigerian-banks-web-1 | go: downloading github.com/rs/cors v1.7.0

nigerian-banks-web-1 | go: github.com/ichtrojan/horus@v1.0.8: missing go.sum entry; to add it:

nigerian-banks-web-1 | go mod download github.com/ichtrojan/horus

root@mycreditchekb2c-mvp-1vcpu-2gb-intel-fra1-01:/nigerian-banks# docker compose ps

NAME COMMAND SERVICE STATUS PORTS
nigerian-banks-web-1 "go run server.go" web exited (1)

**Comment by ichtrojan** [comment]
resolved, there was an external package named `horus` which required extra parameters. however, it has been removed.
