### ISSUE TITLE
Endpoint to fetch a single bank using their slug or code

### ISSUE THREAD

**Issue by kdfemi** [ichtrojan/nigerian-banks#6]
An endpoint that takes a slug or code query param.

**Comment by wizardoma** [comment]
I second this. this will be a very nice addition to this api

**Comment by zikyfranky** [comment]
I thought of making it take params, but decided against it, as the consumer could easily pass both queries and we'd have to deal with priority issues.

So instead, I created 2 endpoints, one for slug, and the other for code, so the consumer knows precisely what they are going for.

You can follow up on the progress here at #18 @wizardoma @kdfemi
